apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-config
  namespace: fraud-detection
data:
  POSTGRES_HOST: pgbouncer
  POSTGRES_PORT: "6432"
  POSTGRES_DB: fraud
  POSTGRES_USER: fraud
  REDIS_ADDR: redis:6379
  NATS_URL: nats://nats:4222
  OTEL_ENDPOINT: jaeger:4317
  WORKER_COUNT: "10"
  LOG_LEVEL: info
