apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fraud-detection

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-init.yaml
  - postgres.yaml
  - redis.yaml
  - nats.yaml
  - pgbouncer.yaml
  - fraud-api.yaml
  - fraud-worker.yaml
  - hpa.yaml
