apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: fraud-detection
spec:
  type: ClusterIP
  selector:
    app: transaction-service
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: fraud-detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: transaction-service
          image: transaction-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_DSN
              value: "postgres://txn:txn@transaction-db:5432/transactions?sslmode=disable"
            - name: FRAUD_GRPC_ADDR
              value: "fraud-api:50051"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
