// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fraud/v1/fraud.proto

package fraudv1

type AssessRequest struct {
	TransactionId string  `json:"transaction_id,omitempty"`
	Amount        float64 `json:"amount,omitempty"`
	Currency      string  `json:"currency,omitempty"`
	SenderId      string  `json:"sender_id,omitempty"`
	ReceiverId    string  `json:"receiver_id,omitempty"`
	DeviceId      string  `json:"device_id,omitempty"`
	Ip            string  `json:"ip,omitempty"`
	Lat           float64 `json:"lat,omitempty"`
	Lng           float64 `json:"lng,omitempty"`
	PaymentMethod string  `json:"payment_method,omitempty"`
	Timestamp     string  `json:"timestamp,omitempty"`
}

type AssessResponse struct {
	TransactionId string   `json:"transaction_id,omitempty"`
	Decision      string   `json:"decision,omitempty"`
	RiskScore     int32    `json:"risk_score,omitempty"`
	Reasons       []string `json:"reasons,omitempty"`
}
