// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: fraud/v1/fraud.proto

package fraudv1

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// FraudServiceClient is the client API for FraudService.
type FraudServiceClient interface {
	Assess(ctx context.Context, in *AssessRequest, opts ...grpc.CallOption) (*AssessResponse, error)
}

type fraudServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFraudServiceClient(cc grpc.ClientConnInterface) FraudServiceClient {
	return &fraudServiceClient{cc}
}

func (c *fraudServiceClient) Assess(ctx context.Context, in *AssessRequest, opts ...grpc.CallOption) (*AssessResponse, error) {
	out := new(AssessResponse)
	err := c.cc.Invoke(ctx, "/fraud.v1.FraudService/Assess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FraudServiceServer is the server API for FraudService.
type FraudServiceServer interface {
	Assess(context.Context, *AssessRequest) (*AssessResponse, error)
	mustEmbedUnimplementedFraudServiceServer()
}

type UnimplementedFraudServiceServer struct{}

func (UnimplementedFraudServiceServer) Assess(context.Context, *AssessRequest) (*AssessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Assess not implemented")
}
func (UnimplementedFraudServiceServer) mustEmbedUnimplementedFraudServiceServer() {}

func RegisterFraudServiceServer(s grpc.ServiceRegistrar, srv FraudServiceServer) {
	s.RegisterService(&FraudService_ServiceDesc, srv)
}

func _FraudService_Assess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudServiceServer).Assess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fraud.v1.FraudService/Assess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudServiceServer).Assess(ctx, req.(*AssessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var FraudService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fraud.v1.FraudService",
	HandlerType: (*FraudServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Assess",
			Handler:    _FraudService_Assess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fraud/v1/fraud.proto",
}
